<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.427">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Meta-Analysis Tutorial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="tutorial_files/libs/clipboard/clipboard.min.js"></script>
<script src="tutorial_files/libs/quarto-html/quarto.js"></script>
<script src="tutorial_files/libs/quarto-html/popper.min.js"></script>
<script src="tutorial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="tutorial_files/libs/quarto-html/anchor.min.js"></script>
<link href="tutorial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="tutorial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="tutorial_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="tutorial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="tutorial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="tutorial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="tutorial_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
<link rel="stylesheet" href="include/booktem.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/glossary.css">
<link rel="stylesheet" href="include/style.css">
<link rel="stylesheet" href="c:/gitbook_stats12/include/webex.css">
</head>
<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#preparing-for-the-workshop" id="toc-preparing-for-the-workshop" class="nav-link active" data-scroll-target="#preparing-for-the-workshop">Preparing for the Workshop</a></li>
  <li>
<a href="#pool" id="toc-pool" class="nav-link" data-scroll-target="#pool">Meta-Analysis in R</a>
  <ul class="collapse">
<li><a href="#using-your-own-data" id="toc-using-your-own-data" class="nav-link" data-scroll-target="#using-your-own-data">Using Your Own Data</a></li>
  <li><a href="#using-different-demo-data" id="toc-using-different-demo-data" class="nav-link" data-scroll-target="#using-different-demo-data">Using Different Demo Data</a></li>
  <li>
<a href="#fixedef" id="toc-fixedef" class="nav-link" data-scroll-target="#fixedef">Fixed Effect Model</a>
  <ul class="collapse">
<li><a href="#fixed-effects-model-with-rma" id="toc-fixed-effects-model-with-rma" class="nav-link" data-scroll-target="#fixed-effects-model-with-rma">Fixed-effects Model with <code>rma</code></a></li>
  </ul>
</li>
  <li><a href="#random" id="toc-random" class="nav-link" data-scroll-target="#random">Random-Effects-Model</a></li>
  <li><a href="#random-effects-model-with-rma" id="toc-random-effects-model-with-rma" class="nav-link" data-scroll-target="#random-effects-model-with-rma">Random-Effects Model with <code>rma</code></a></li>
  </ul>
</li>
  <li>
<a href="#metareg" id="toc-metareg" class="nav-link" data-scroll-target="#metareg">Meta-Regression</a>
  <ul class="collapse">
<li><a href="#testing-moderators-significance" id="toc-testing-moderators-significance" class="nav-link" data-scroll-target="#testing-moderators-significance">Testing Moderators’ Significance</a></li>
  <li><a href="#assessing-meta-regression-model-fit" id="toc-assessing-meta-regression-model-fit" class="nav-link" data-scroll-target="#assessing-meta-regression-model-fit">Assessing Meta-Regression Model Fit</a></li>
  <li>
<a href="#meta-regression-in-r" id="toc-meta-regression-in-r" class="nav-link" data-scroll-target="#meta-regression-in-r">Meta-regression in R</a>
  <ul class="collapse">
<li><a href="#continuous-predictors" id="toc-continuous-predictors" class="nav-link" data-scroll-target="#continuous-predictors">Continuous Predictors</a></li>
  <li><a href="#multiple-meta-regression" id="toc-multiple-meta-regression" class="nav-link" data-scroll-target="#multiple-meta-regression">Multiple Meta-Regression</a></li>
  </ul>
</li>
  <li>
<a href="#optional-pitfalls-of-meta-regression" id="toc-optional-pitfalls-of-meta-regression" class="nav-link" data-scroll-target="#optional-pitfalls-of-meta-regression">Optional: Pitfalls of Meta-Regression</a>
  <ul class="collapse">
<li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity">Multicollinearity</a></li>
  <li><a href="#overfitting" id="toc-overfitting" class="nav-link" data-scroll-target="#overfitting">Overfitting</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#penalized-meta-regression" id="toc-penalized-meta-regression" class="nav-link" data-scroll-target="#penalized-meta-regression">Penalized Meta-Regression</a>
  <ul class="collapse">
<li>
<a href="#two-level-model" id="toc-two-level-model" class="nav-link" data-scroll-target="#two-level-model">Two-level model</a>
  <ul class="collapse">
<li><a href="#two-level-model-with-the-lasso-prior" id="toc-two-level-model-with-the-lasso-prior" class="nav-link" data-scroll-target="#two-level-model-with-the-lasso-prior">Two-level model with the lasso prior</a></li>
  </ul>
</li>
  <li>
<a href="#optional-three-level-model-with-horseshoe-prior" id="toc-optional-three-level-model-with-horseshoe-prior" class="nav-link" data-scroll-target="#optional-three-level-model-with-horseshoe-prior">Optional: Three-level model with Horseshoe Prior</a>
  <ul class="collapse">
<li><a href="#more-information" id="toc-more-information" class="nav-link" data-scroll-target="#more-information">More Information</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#random-forest-meta-regression" id="toc-random-forest-meta-regression" class="nav-link" data-scroll-target="#random-forest-meta-regression">Random Forest Meta-Regression</a>
  <ul class="collapse">
<li><a href="#check-convergence" id="toc-check-convergence" class="nav-link" data-scroll-target="#check-convergence">Check Convergence</a></li>
  <li><a href="#model-tuning" id="toc-model-tuning" class="nav-link" data-scroll-target="#model-tuning">Model Tuning</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results">Interpreting the Results</a></li>
  <li><a href="#more-information-1" id="toc-more-information-1" class="nav-link" data-scroll-target="#more-information-1">More Information</a></li>
  </ul>
</li>
  <li>
<a href="#bayesian-evidence-synthesis" id="toc-bayesian-evidence-synthesis" class="nav-link" data-scroll-target="#bayesian-evidence-synthesis">Bayesian Evidence Synthesis</a>
  <ul class="collapse">
<li><a href="#repeating-the-rma" id="toc-repeating-the-rma" class="nav-link" data-scroll-target="#repeating-the-rma">Repeating the RMA</a></li>
  <li><a href="#product-bayes-factor" id="toc-product-bayes-factor" class="nav-link" data-scroll-target="#product-bayes-factor">Product Bayes Factor</a></li>
  <li><a href="#more-information-2" id="toc-more-information-2" class="nav-link" data-scroll-target="#more-information-2">More Information</a></li>
  <li><a href="#credit" id="toc-credit" class="nav-link" data-scroll-target="#credit">Credit</a></li>
  </ul>
</li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Meta-Analysis Tutorial</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="preparing-for-the-workshop" class="level1 smaller"><h1 class="smaller">Preparing for the Workshop</h1>
<ol type="1">
<li>Install R and then RStudio
<ul>
<li>Follow the instructions here: <a href="https://posit.co/download/rstudio-desktop/" class="uri">https://posit.co/download/rstudio-desktop/</a>
</li>
</ul>
</li>
<li>Open RStudio.<br>
Now, run the setup script for this workshop.<br>
In the window labeled “Console”, paste this code and press [Enter]:</li>
</ol>
<pre><code>source("https://raw.githubusercontent.com/cjvanlissa/meta_workshop/refs/heads/master/check_function.R")</code></pre>
<ol start="3" type="1">
<li>If you have your own data: after running the <code><a href="https://rdrr.io/r/base/source.html">source()</a></code> command above, you can use the function <code>check_data()</code>.
<ul>
<li>Load your own data into R as usual, and check if you can use it for the workshop exercises by running:</li>
<li><code>check_data(your_data_object)</code></li>
</ul>
</li>
</ol></section><section id="pool" class="level1"><h1>Meta-Analysis in R</h1>
<p>The essence of Meta-Analysis is <strong>pooling your effect sizes</strong> to get an overall effect size estimate of the studies.</p>
<p>When pooling effect sizes in Meta-Analysis, there are two basic approaches: the <strong>Fixed-Effect-Model</strong>, or the <strong>Random-Effects-Model</strong> <span class="citation" data-cites="borensteinIntroductionMetaAnalysis2009">(<a href="#ref-borensteinIntroductionMetaAnalysis2009" role="doc-biblioref">Borenstein et al., 2009</a>)</span>. The fixed effect model assumes that one true effect size exists in the population; the random effects model assumes that the true effect varies (and is normally distributed).</p>
<p>Both of these models require an <strong>effect size</strong>, and a <strong>dispersion (variance)</strong> estimate for each study.</p>
<p>For these meta-analyses, we’ll use the <code>metafor</code> package <span class="citation" data-cites="viechtbauerConductingMetaanalysesMetafor2010">(<a href="#ref-viechtbauerConductingMetaanalysesMetafor2010" role="doc-biblioref">Viechtbauer, 2010</a>)</span>. However, notice that we load a different package, <code>metaforest</code>. The reason is that it contains the example data for this tutorial, and it loads the <code>metafor</code> package in turn.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">metaforest</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="using-your-own-data" class="level3"><h3 class="anchored" data-anchor-id="using-your-own-data">Using Your Own Data</h3>
<p>If you want, you can conduct the examples below with your own data. Note that the interactive questions won’t work in this case (the correct answers are based on the <code>curry</code> data).</p>
<p>If you want to use your own data, you can use the function <code>check_data()</code> to help make sure that your data are suitable for the tutorial examples. Install the function by running:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/cjvanlissa/meta_workshop/refs/heads/master/check_function.R"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, apply the function to your data object by running <code>check_data(your_data_object)</code>. It will give helpful suggestions to make it easier to follow the tutorial with your own data:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">curry</span></span>
<span><span class="fu">check_data</span><span class="op">(</span><span class="va">df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>• There is no column named 'yi' in your data. If you have an effect size column, it will be easier to do the tutorial if you rename it, using syntax like this:
  
  names(df)[which(names(df) == 'youreffectsize')] &lt;- 'yi'
  
  If you do not yet have an effect size column, you may need to compute it first. Run ?metafor::escalc to see the help for this function.</code></pre>
</div>
</div>
<p>Note that the message suggests that we rename the effect size column, which is called <code>d</code> in the <code>curry</code> dataset, to <code>yi</code>. Let’s do that:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">==</span> <span class="st">'d'</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="st">'yi'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="using-different-demo-data" class="level3"><h3 class="anchored" data-anchor-id="using-different-demo-data">Using Different Demo Data</h3>
<p>If you do not have your own data but are up for a challenge, you can use a different demo dataset to complete the tutorial. Two suggestions are:</p>
<pre><code><a href="https://rdrr.io/pkg/metaforest/man/fukkink_lont.html">metaforest::fukkink_lont
pema::bonapersona</a></code></pre>
</section><section id="fixedef" class="level2"><h2 class="anchored" data-anchor-id="fixedef">Fixed Effect Model</h2>
<p><strong>The idea behind the fixed-effects-model</strong></p>
<p>The fixed-effects-model assumes that all observed effect sizes stem from a single <em>true</em> population effect <span class="citation" data-cites="borensteinIntroductionMetaAnalysis2009">(<a href="#ref-borensteinIntroductionMetaAnalysis2009" role="doc-biblioref">Borenstein et al., 2009</a>)</span>. To calculate the overall effect, we therefore average all effect sizes, but give studies with greater precision a higher weight. Precision relates to the fact that studies with a smaller <strong>Standard Error</strong> provide more accurate estimates of the true population effect.</p>
<p>For this weighing, we use the <strong>inverse of the variance</strong> <span class="math inline">\(1/\hat\sigma^2_k\)</span> of each study <span class="math inline">\(k\)</span>. We then calculate a weighted average of all studies, our fixed effect size estimator <span class="math inline">\(\hat\theta_F\)</span>:</p>
<p><span class="math display">\[
\begin{equation}
\hat\theta_F = \frac{\sum\limits_{k=1}^K \hat\theta_k/ \hat\sigma^2_k}{\sum\limits_{k=1}^K 1/\hat\sigma^2_k}
\end{equation}
\]</span></p>
<p>These examples assume you already have a dataset with the <strong>calucated effects and SE</strong> for each study. The <code>curry</code> data set, inside the <code>metaforest</code> package, will do. This dataset already contains the effect sizes and their variances, so we can directly use the <code>rma</code> function.</p>
<section id="fixed-effects-model-with-rma" class="level3"><h3 class="anchored" data-anchor-id="fixed-effects-model-with-rma">Fixed-effects Model with <code>rma</code>
</h3>
<p>The <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma()</a></code> function has many arguments, all of which you can accessed by typing <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">?rma</a></code> in your console once the <code>metafor</code> package is loaded, or selecting the function and pressing F1.</p>
<p><strong>Here is a table with the most important arguments for our code:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 91%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">Argument</th>
<th style="text-align: left;">Function</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">yi</td>
<td style="text-align: left;">A vector with the effect sizes</td>
</tr>
<tr class="even">
<td style="text-align: left;">vi</td>
<td style="text-align: left;">A vector with the sampling variances</td>
</tr>
<tr class="odd">
<td style="text-align: left;">method</td>
<td style="text-align: left;">A character string, indicating what type of meta-analysis to run. FE runs a fixed-effect model</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let’s conduct our first fixed-effects-model Meta-Analysis. We we will give the results of this analysis the simple name <code>m</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">yi</span>,     <span class="co"># The yi-column of the df, which contains Cohen's d</span></span>
<span>         vi <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">vi</span>,    <span class="co"># The vi-column of the df, which contains the variances</span></span>
<span>         method <span class="op">=</span> <span class="st">"FE"</span><span class="op">)</span> <span class="co"># Run a fixed-effect model</span></span>
<span><span class="va">m</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Fixed-Effects Model (k = 56)

I^2 (total heterogeneity / total variability):   64.95%
H^2 (total variability / sampling variability):  2.85

Test for Heterogeneity:
Q(df = 55) = 156.9109, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2059  0.0219  9.4135  &lt;.0001  0.1630  0.2487  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We now see a summary of the results of our Meta-Analysis, including</p>
<ul>
<li>The total <strong>number of included studies</strong> (k)</li>
<li>The <strong>overall effect</strong>, its confidence interval and p-value</li>
<li>The <em>Q</em>-test of heterogeneity</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>How big is the overall effect? <input class="webex-solveme nospaces" data-tol="0.01" size="5" data-answer="[&quot;0.206&quot;,&quot;.206&quot;]"></p>
<p>True or false: A significant proportion of the variability in effect sizes is attributable to heterogeneity, rather than sampling error. <select class="webex-select"><option value="blank"></option>
<option value="answer">TRUE</option>
<option value="">FALSE</option></select></p>
<p>What can you say about the heterogeneity of the population effect? <select class="webex-select"><option value="blank"></option>
<option value="">Can’t say anything based on this output</option>
<option value="answer">It is assumed to be zero</option>
<option value="">It is significant, Q(55) = 156,91, p &lt; .0001</option>
<option value="">It is large, I2 = 64.95%</option></select></p>
</div>
</div>
</section></section><section id="random" class="level2"><h2 class="anchored" data-anchor-id="random">Random-Effects-Model</h2>
<p>We can only use the fixed-effect-model when we can assume that <strong>all included studies tap into one true effect size</strong>. In practice this is hardly ever the case: interventions may vary in certain characteristics, the sample used in each study might be slightly different, or its methods. If we can assume that there are many small, random, uncorrelated variations in true effect sizes, then a more appropriate assumption in these cases might be that the true effect size follows a normal distribution.</p>
<p><strong>The Idea behind the Random-Effects-Model</strong></p>
<p>In the Random-Effects-Model, we want to account for our assumption that the population effect size is normally distributed <span class="citation" data-cites="schwarzerMetaAnalysis2015">(<a href="#ref-schwarzerMetaAnalysis2015" role="doc-biblioref">Schwarzer et al., 2015</a>)</span>.</p>
<p>The fixed-effect-model assumes that when the observed effect size <span class="math inline">\(\hat\theta_k\)</span> of an individual study <span class="math inline">\(k\)</span> deviates from the true effect size <span class="math inline">\(\theta_F\)</span>, the only reason for this is that the estimate is burdened by (sampling) error <span class="math inline">\(\epsilon_k\)</span>.</p>
<p><span class="math display">\[\hat\theta_k = \theta_F + \epsilon_k\]</span></p>
<p>While the random-effects-model assumes that, in addition, there is <strong>a second source of error</strong> <span class="math inline">\(\zeta_k\)</span>.This second source of error is introduced by the fact that even the true effect size <span class="math inline">\(\theta_k\)</span> of our study <span class="math inline">\(k\)</span> is also only part of an over-arching distribution of true effect sizes with the mean <span class="math inline">\(\mu\)</span> <span class="citation" data-cites="borensteinIntroductionMetaAnalysis2009">(<a href="#ref-borensteinIntroductionMetaAnalysis2009" role="doc-biblioref">Borenstein et al., 2009</a>)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="tutorial_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p style="text-align: center;">
<em>An illustration of parameters of the random-effects-model</em>
</p>
<p>The formula for the random-effects-model therefore looks like this:</p>
<p><span class="math display">\[\hat\theta_k = \mu + \epsilon_k + \zeta_k\]</span></p>
<p>When calculating a random-effects-model meta-analysis, where therefore also have to take the error <span class="math inline">\(\zeta_k\)</span> into account. To do this, we have to <strong>estimate the variance of the distribution of true effect sizes</strong>, which is denoted by <span class="math inline">\(\tau^{2}\)</span>, or <em>tau<sup>2</sup></em>. There are several estimators for <span class="math inline">\(\tau^{2}\)</span>, all of which are implemented in <code>metafor</code>.</p>
</section><section id="random-effects-model-with-rma" class="level2"><h2 class="anchored" data-anchor-id="random-effects-model-with-rma">Random-Effects Model with <code>rma</code>
</h2>
<p>We can re-use our code from the fixed-effects-model and simply remove the <code>method = "FE"</code> argument to conduct a random-effects analysis with the default REML estimator for <span class="math inline">\(\tau^2\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_re</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">yi</span>,     <span class="co"># The yi-column of the df, which contains Cohen's d</span></span>
<span>            vi <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">vi</span><span class="op">)</span>    <span class="co"># The vi-column of the df, which contains the variances</span></span>
<span><span class="va">m_re</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 56; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0570 (SE = 0.0176)
tau (square root of estimated tau^2 value):      0.2388
I^2 (total heterogeneity / total variability):   67.77%
H^2 (total variability / sampling variability):  3.10

Test for Heterogeneity:
Q(df = 55) = 156.9109, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2393  0.0414  5.7805  &lt;.0001  0.1581  0.3204  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>How big is the overall effect? <input class="webex-solveme nospaces" data-tol="0.01" size="4" data-answer="[&quot;0.24&quot;,&quot;.24&quot;]"></p>
<p>What is the estimated heterogeneity? <input class="webex-solveme nospaces" data-tol="0.01" size="4" data-answer="[&quot;0.06&quot;,&quot;.06&quot;]">.</p>
<p>What can you say about the the expected value of the population effect in the random-effects model, compared to the previous fixed-effect model? <select class="webex-select"><option value="blank"></option>
<option value="">Can’t say anything based on this output</option>
<option value="answer">It is larger</option>
<option value="">It is about the same</option>
<option value="">It is smaller</option></select></p>
<p>This is caused by the fact that random-effects models assign more equal weight to all studies, including small ones, which tend to be more biased.</p>
</div>
</div>
</section></section><section id="metareg" class="level1"><h1>Meta-Regression</h1>
<p><strong>The idea behind meta-regression</strong></p>
<p>In a conventional regression, we specify a model predicting the dependent variable <span class="math inline">\(y\)</span>, across <span class="math inline">\(_i\)</span> participants, based on their values on <span class="math inline">\(p\)</span> predictor variables, <span class="math inline">\(x_{i1} \dots x_{ip}\)</span>. The residual error is referred to as <span class="math inline">\(\epsilon_i\)</span>. A standard regression equation therefore looks like this:</p>
<p><span class="math display">\[y_i=\beta_0 + \beta_1x_{1i} + ...+\beta_px_{pi} + \epsilon_i\]</span></p>
<p>In a meta-regression, we want to estimate the <strong>effect size</strong> <span class="math inline">\(\theta\)</span> of several studies <span class="math inline">\(_k\)</span>, as a function of between-studies moderators. There are two sources of heterogeneity: sampling error, <span class="math inline">\(\epsilon_k\)</span>, and between-studies heterogeneity, <span class="math inline">\(\zeta_k\)</span> so our regression looks like this:</p>
<p><span class="math display">\[\theta_k = \beta_0 + \beta_1x_{1k} + ... + \beta_px_{pk} + \epsilon_k + \zeta_k\]</span></p>
<p>You might have seen that when estimating the effect size <span class="math inline">\(\theta_k\)</span> of a study <span class="math inline">\(k\)</span> in our regression model, there are two <strong>extra terms in the equation</strong>, <span class="math inline">\(\epsilon_k\)</span> and <span class="math inline">\(\zeta_k\)</span>. The same terms can also be found in the equation for the random-effects model. The two terms signify two types of <strong>independent errors</strong> which cause our regression prediction to be <strong>imperfect</strong>. The first one, <span class="math inline">\(\epsilon_k\)</span>, is the sampling error through which the effect size of the study deviates from its “true” effect. The second one, <span class="math inline">\(\zeta_k\)</span>, denotes that even the true effect size of the study is only sampled from <strong>an overarching distribution of effect sizes</strong>.</p>
<p>As the equation above has includes <strong>fixed effects</strong> (the <span class="math inline">\(\beta\)</span> coefficients) as well as <strong>random effects</strong> (<span class="math inline">\(\zeta_k\)</span>), the model used in meta-regression is often called <strong>a mixed-effects-model</strong>.</p>
<section id="testing-moderators-significance" class="level3"><h3 class="anchored" data-anchor-id="testing-moderators-significance">Testing Moderators’ Significance</h3>
<p>To evaluate the <strong>statistical significance of a predictor</strong>, we conduct a <strong>t-test</strong> (or Z-test) of its <span class="math inline">\(\beta\)</span>-weight.</p>
<p><span class="math display">\[ t=\frac{\beta}{SE_{\beta}}\]</span></p>
<p>Which provides a <span class="math inline">\(p\)</span>-value telling us if a variable significantly predicts effect size differences in our regression model.</p>
</section><section id="assessing-meta-regression-model-fit" class="level3"><h3 class="anchored" data-anchor-id="assessing-meta-regression-model-fit">Assessing Meta-Regression Model Fit</h3>
<p>In conventional regression, <span class="math inline">\(R^2\)</span> is commonly used to quantify the percentage of variance in the data explained by the model, as a percentage of total variance (0-100%). As this measure is commonly used, and many researchers know how to to interpret it, we can also calculate a <span class="math inline">\(R^2\)</span> analog for meta-regression using this formula:</p>
<p><span class="math display">\[R_2=\frac{\hat\tau^2_{REM}-\hat\tau^2_{MEM}}{\hat\tau^2_{REM}}\]</span></p>
<p>Where <span class="math inline">\(\hat\tau^2_{REM}\)</span> is the estimated total heterogenetiy based on the random-effects-model and <span class="math inline">\(\hat\tau^2_{REM}\)</span> the total heterogeneity of our mixed-effects regression model.</p>
<p>NOTE however, that <span class="math inline">\(R^2\)</span> refers to variance explained in the observed data. In linear regression, the more predictors you add, the better your model will explain the observed data. But this can decrease the generalizability of you model, through a process called <strong>overfitting</strong>: You’re capturing noise in your dataset, not true effects that exist in the real world. In meta-regression, because the estimate of heterogeneity may differ, we may not actually see the <span class="math inline">\(R^2\)</span> increasing with more predictors - but because the samples are often small, be very mindful of overfitting nonetheless.</p>
</section><section id="meta-regression-in-r" class="level2"><h2 class="anchored" data-anchor-id="meta-regression-in-r">Meta-regression in R</h2>
<p>Meta-regressions can be conducted in R using the <code>rma</code> function in <code>metafor</code>. First, let’s conduct a regression with a single categorical predictor, <code>donorcode</code>, which has two levels: <code>Anxious</code> and <code>Typical</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_cat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span><span class="va">yi</span> <span class="op">~</span> <span class="va">donorcode</span>, vi <span class="op">=</span> <span class="va">vi</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="va">m_cat</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 56; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0567 (SE = 0.0177)
tau (square root of estimated tau^2 value):             0.2382
I^2 (residual heterogeneity / unaccounted variability): 67.81%
H^2 (unaccounted variability / sampling variability):   3.11
R^2 (amount of heterogeneity accounted for):            0.49%

Test for Residual Heterogeneity:
QE(df = 54) = 155.0054, p-val &lt; .0001

Test of Moderators (coefficient 2):
QM(df = 1) = 1.5257, p-val = 0.2168

Model Results:

                  estimate      se    zval    pval    ci.lb   ci.ub    
intrcpt             0.0829  0.1332  0.6222  0.5338  -0.1781  0.3439    
donorcodeTypical    0.1730  0.1401  1.2352  0.2168  -0.1015  0.4476    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>By default, <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">metafor::rma()</a></code> will recode <code>factor</code> variables to make one group the reference category and create dummies for all other groups. The syntax above created a binary indicator variable (a dummy variable) for people who fall in the <code>Typical</code> category. It then estimated the model intercept - which is the population effect size in the <code>Anxious</code> category, which serves as reference category here, and the effect of the <code>donorcodeTypical</code> dummy, which tells us the difference between the two groups’ population effects.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is the expected population effect size in the Typical group? <input class="webex-solveme nospaces" data-tol="0.01" size="4" data-answer="[&quot;0.17&quot;,&quot;.17&quot;]"></p>
<p>What is the expected population effect size in the Anxious group? <input class="webex-solveme nospaces" data-tol="0.01" size="8" data-answer="[&quot;0.255888&quot;,&quot;.255888&quot;]">.</p>
<p>True or false: There is a significant difference between the two groups. <select class="webex-select"><option value="blank"></option>
<option value="">TRUE</option>
<option value="answer">FALSE</option></select></p>
</div>
</div>
<section id="continuous-predictors" class="level3"><h3 class="anchored" data-anchor-id="continuous-predictors">Continuous Predictors</h3>
<p>Imagine you want to check if the <strong>proportion of male participants</strong> is associated with effect size. The variable <code>sex</code> contains this information. You can use this predictor in a meta-regression:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_reg</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span><span class="va">yi</span> <span class="op">~</span><span class="va">sex</span>,</span>
<span>             vi <span class="op">=</span> <span class="va">vi</span>,</span>
<span>             data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="va">m_reg</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 56; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0544 (SE = 0.0173)
tau (square root of estimated tau^2 value):             0.2333
I^2 (residual heterogeneity / unaccounted variability): 66.50%
H^2 (unaccounted variability / sampling variability):   2.98
R^2 (amount of heterogeneity accounted for):            4.53%

Test for Residual Heterogeneity:
QE(df = 54) = 149.5878, p-val &lt; .0001

Test of Moderators (coefficient 2):
QM(df = 1) = 2.1607, p-val = 0.1416

Model Results:

         estimate      se    zval    pval    ci.lb   ci.ub    
intrcpt    0.0648  0.1253  0.5168  0.6053  -0.1808  0.3104    
sex        0.0050  0.0034  1.4699  0.1416  -0.0017  0.0116    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>True or false: There is a significant effect of sex. <select class="webex-select"><option value="blank"></option>
<option value="">TRUE</option>
<option value="answer">FALSE</option></select></p>
<p>How to interpret the effect of sex? <select class="webex-select"><option value="blank"></option>
<option value="">There is no effect of sex</option>
<option value="answer">A one-percent increase in male participants is associated with a .005 point increase in the population effect</option>
<option value="">The difference between men and women is .005</option>
<option value="">Can’t say based on this output</option></select></p>
</div>
</div>
</section><section id="multiple-meta-regression" class="level3"><h3 class="anchored" data-anchor-id="multiple-meta-regression">Multiple Meta-Regression</h3>
<p>Previously, we only considered the scenario in which we use <strong>one predictor</strong> <span class="math inline">\(\beta_1x_1\)</span> in our meta-regression. When we add more than one predictor, we’re using <strong>multiple meta-regression</strong>. In multiple meta-regression we use several moderators (variables) to predict the outcome (effect sizes). When we look back at the <strong>general meta-regression</strong> formula we defined before, we actually see that the formula already provides us with this feature through the <span class="math inline">\(\beta_nx_{pk}\)</span> part. Here, the parameter <span class="math inline">\(p\)</span> denotes that we can include <span class="math inline">\(p\)</span> more predictors/variables into our meta-regression, making it a multiple meta-regression.</p>
<p>We could include both predictors from the previous exercises in a mutliple meta-regression as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_multi</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span><span class="va">yi</span> <span class="op">~</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">donorcode</span>,</span>
<span>               vi <span class="op">=</span> <span class="va">vi</span>,</span>
<span>               data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="va">m_multi</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 56; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0551 (SE = 0.0175)
tau (square root of estimated tau^2 value):             0.2347
I^2 (residual heterogeneity / unaccounted variability): 66.89%
H^2 (unaccounted variability / sampling variability):   3.02
R^2 (amount of heterogeneity accounted for):            3.42%

Test for Residual Heterogeneity:
QE(df = 53) = 148.6166, p-val &lt; .0001

Test of Moderators (coefficients 2:3):
QM(df = 2) = 3.0602, p-val = 0.2165

Model Results:

                  estimate      se     zval    pval    ci.lb   ci.ub    
intrcpt            -0.0337  0.1626  -0.2074  0.8357  -0.3523  0.2849    
sex                 0.0043  0.0035   1.2310  0.2183  -0.0025  0.0111    
donorcodeTypical    0.1361  0.1421   0.9579  0.3381  -0.1424  0.4146    

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Now, let’s create a model that includes <em>all</em> potential moderators of the effect size:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mods</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sex"</span>, <span class="st">"age"</span>, <span class="st">"location"</span>, <span class="st">"donorcode"</span>, <span class="st">"interventioncode"</span>, <span class="st">"controlcode"</span>, <span class="st">"recipients"</span>, <span class="st">"outcomecode"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">res_multi2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/formula.html">as.formula</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"yi ~"</span>, <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">mods</span>, collapse <span class="op">=</span> <span class="st">"+"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, vi <span class="op">=</span> <span class="va">vi</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Redundant predictors dropped from the model.</code></pre>
</div>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_multi2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 56; tau^2 estimator: REML)

tau^2 (estimated amount of residual heterogeneity):     0.0038 (SE = 0.0076)
tau (square root of estimated tau^2 value):             0.0618
I^2 (residual heterogeneity / unaccounted variability): 12.55%
H^2 (unaccounted variability / sampling variability):   1.14
R^2 (amount of heterogeneity accounted for):            93.30%

Test for Residual Heterogeneity:
QE(df = 26) = 34.1905, p-val = 0.1303

Test of Moderators (coefficients 2:30):
QM(df = 29) = 105.3506, p-val &lt; .0001

Model Results:

                                    estimate      se     zval    pval    ci.lb 
intrcpt                              -0.2964  0.8410  -0.3525  0.7245  -1.9448 
sex                                   0.0044  0.0110   0.3992  0.6897  -0.0172 
age                                   0.0128  0.0100   1.2832  0.1994  -0.0068 
locationCanada                        0.8634  1.0422   0.8284  0.4075  -1.1794 
locationCanada / South Africa         0.0560  0.5842   0.0959  0.9236  -1.0889 
locationGermany                       0.5554  0.7777   0.7142  0.4751  -0.9688 
locationNetherlands                   1.1263  1.1876   0.9484  0.3429  -1.2013 
locationSpain                        -0.2568  0.4047  -0.6346  0.5257  -1.0501 
locationUK?                           1.0766  0.9283   1.1598  0.2461  -0.7427 
locationUSA                           0.1954  0.5615   0.3479  0.7279  -0.9052 
locationUSA/Korea                     0.9159  0.8915   1.0273  0.3043  -0.8315 
locationVanuatu                       0.6234  1.0167   0.6132  0.5398  -1.3693 
donorcodeTypical                     -0.0402  0.1268  -0.3169  0.7513  -0.2886 
interventioncodeOther                 0.5408  0.4922   1.0988  0.2719  -0.4238 
interventioncodeProsocial Spending    0.1450  0.3452   0.4201  0.6744  -0.5316 
controlcodeNothing                    0.0400  0.2505   0.1596  0.8732  -0.4510 
controlcodeSelf Help                 -0.0652  0.0936  -0.6966  0.4860  -0.2488 
recipientsAnyone                     -0.9105  0.6852  -1.3288  0.1839  -2.2534 
recipientsAnyone / Charity           -0.3069  0.6165  -0.4978  0.6186  -1.5152 
recipientsCharity                    -0.3874  0.3367  -1.1507  0.2499  -1.0472 
recipientsColleague                  -1.9522  0.5006  -3.8997  &lt;.0001  -2.9334 
recipientsFamily / Friends           -0.2505  0.9360  -0.2676  0.7890  -2.0850 
recipientsOther/One                   0.0803  0.1801   0.4460  0.6556  -0.2727 
recipientsOther/World                -0.2009  0.3779  -0.5315  0.5951  -0.9416 
recipientsPuppet                     -0.8931  0.5496  -1.6251  0.1041  -1.9703 
recipientsSocial Network             -0.3611  0.5046  -0.7156  0.4743  -1.3501 
recipientsSomeone                    -0.8046  0.6648  -1.2104  0.2261  -2.1075 
outcomecodeLife Satisfaction          0.0634  0.1135   0.5589  0.5763  -0.1590 
outcomecodeOther                      0.0198  0.0865   0.2284  0.8194  -0.1498 
outcomecodePN Affect                  0.0530  0.0910   0.5824  0.5603  -0.1253 
                                      ci.ub      
intrcpt                              1.3519      
sex                                  0.0259      
age                                  0.0324      
locationCanada                       2.9061      
locationCanada / South Africa        1.2009      
locationGermany                      2.0797      
locationNetherlands                  3.4540      
locationSpain                        0.5364      
locationUK?                          2.8960      
locationUSA                          1.2960      
locationUSA/Korea                    2.6633      
locationVanuatu                      2.6161      
donorcodeTypical                     0.2083      
interventioncodeOther                1.5054      
interventioncodeProsocial Spending   0.8216      
controlcodeNothing                   0.5310      
controlcodeSelf Help                 0.1183      
recipientsAnyone                     0.4325      
recipientsAnyone / Charity           0.9014      
recipientsCharity                    0.2725      
recipientsColleague                 -0.9711  *** 
recipientsFamily / Friends           1.5841      
recipientsOther/One                  0.4334      
recipientsOther/World                0.5399      
recipientsPuppet                     0.1841      
recipientsSocial Network             0.6279      
recipientsSomeone                    0.4983      
outcomecodeLife Satisfaction         0.2859      
outcomecodeOther                     0.1893      
outcomecodePN Affect                 0.2313      

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is the number of studies included in the second multiple meta-regression (with all predictors)? <input class="webex-solveme nospaces" size="2" data-answer="[&quot;56&quot;]"></p>
<p>What is the number of parameters of the second multiple meta-regression (with all predictors)? <input class="webex-solveme nospaces" size="2" data-answer="[&quot;30&quot;]"></p>
<p>The <span class="math inline">\(R^2\)</span> of the second multiple meta-regression model is 93.30%. How can we interpret this? <select class="webex-select"><option value="blank"></option>
<option value="">As a large effect; there must be several significant moderators.</option>
<option value="answer">With caution; the model is likely overfit.</option>
<option value="">As a large effect; the moderators explain most of the heterogeneity.</option>
<option value="">Can’t say based on this output</option></select></p>
</div>
</div>
</section></section><section id="optional-pitfalls-of-meta-regression" class="level2"><h2 class="anchored" data-anchor-id="optional-pitfalls-of-meta-regression">Optional: Pitfalls of Meta-Regression</h2>
<p>Skip this section if you are pressed for time.</p>
<section id="multicollinearity" class="level3"><h3 class="anchored" data-anchor-id="multicollinearity">Multicollinearity</h3>
<p>When performing the analysis above, we saw a warning message:</p>
<p><font color="red"> Warning: Redundant predictors dropped from the model. </font></p>
<p>This warning tells us that some of the moderators conveyed exactly the same information, and therefore, it’s not possible to include both in the same model.</p>
<p>For example, look at the following subset of the data. Imagine that this would be our entire dataset:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">24</span>, <span class="fl">28</span>, <span class="fl">46</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"age"</span>, <span class="st">"location"</span>, <span class="st">"interventioncode"</span>, <span class="st">"controlcode"</span>, <span class="st">"outcomecode"</span><span class="op">)</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 28%">
<col style="width: 25%">
<col style="width: 18%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">location</th>
<th style="text-align: left;">interventioncode</th>
<th style="text-align: left;">controlcode</th>
<th style="text-align: left;">outcomecode</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">21.00</td>
<td style="text-align: left;">Canada</td>
<td style="text-align: left;">Prosocial Spending</td>
<td style="text-align: left;">Self Help</td>
<td style="text-align: left;">Other</td>
</tr>
<tr class="even">
<td style="text-align: left;">24</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: left;">Canada</td>
<td style="text-align: left;">Prosocial Spending</td>
<td style="text-align: left;">Self Help</td>
<td style="text-align: left;">Happiness</td>
</tr>
<tr class="odd">
<td style="text-align: left;">28</td>
<td style="text-align: right;">18.55</td>
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Acts of Kindness</td>
<td style="text-align: left;">Neutral Activity</td>
<td style="text-align: left;">Other</td>
</tr>
<tr class="even">
<td style="text-align: left;">46</td>
<td style="text-align: right;">29.95</td>
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Acts of Kindness</td>
<td style="text-align: left;">Neutral Activity</td>
<td style="text-align: left;">Other</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Note that the variable <code>age</code> has unique values for each study, but the first two and second two studies are completely identical in the variables <code>location</code>, <code>interventioncode</code>, and <code>controlcode</code>. If this was our dataset, it would thus not be possible to determine a unique effect for any of these three variables (because they overlap completely). This is an example of (multi)colinearity. Even more worrying: the column <code>outcomecode</code> almost has the same value for each study. If it did, then this column would be redundant with the model’s intercept! It would no longer be a variable, but a constant. As it stands, only one study is distinct in <code>outcomecode</code>. If we add a dummy for this variable - that dummy uniquely identifies that one study (which means the model will perfectly reproduce its value)!</p>
</section><section id="overfitting" class="level3"><h3 class="anchored" data-anchor-id="overfitting">Overfitting</h3>
<p>To better understand the risks of (multiple) meta-regression models, we have to understand the concept of <strong>overfitting</strong>. Overfitting occurs when we build a statistical model which fits the data <strong>too closely</strong>. In essence, this means that we build a statistical model which can predict the data at hand very well, but performs bad at predicting future data it has never seen before. This happens if our model assumes that some variation in our data <strong>stems from a true “signal” in our data, when in fact we only model random noise</strong> <span class="citation" data-cites="hastieElementsStatisticalLearning2009">(<a href="#ref-hastieElementsStatisticalLearning2009" role="doc-biblioref">Hastie et al., 2009</a>)</span>. As a result, our statistical model produces <strong>false positive results</strong>: it sees relationships where there are none.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="./materials/overfitting.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Illustration of an overfitted model vs.&nbsp;model with a good fit</figcaption></figure>
</div>
<p>Regression methods, which usually utilize minimization or maximization procedures such as Ordinary Least Squares or Maximum Likelihood estimatation, can be prone to overfitting <span class="citation" data-cites="hastieElementsStatisticalLearning2009">(<a href="#ref-hastieElementsStatisticalLearning2009" role="doc-biblioref">Hastie et al., 2009</a>)</span>. Unfortunately, the risk of building a <strong>non-robust model, which produces false-positive results</strong>, is <strong>even higher</strong> once we go from conventional regression to <strong>meta-regression</strong> <span class="citation" data-cites="higginsControllingRiskSpurious2004">(<a href="#ref-higginsControllingRiskSpurious2004" role="doc-biblioref">J. P. T. Higgins &amp; Thompson, 2004</a>)</span>. There are several reasons for this:</p>
<ol type="1">
<li>In Meta-Regression, our <strong>sample is often small</strong>, as we can only use the synthesized data of all analyzed studies <span class="math inline">\(k\)</span>.</li>
<li>As our meta-analysis aims to be a <strong>comprehensive overview of all evidence</strong>, we have no <strong>additional data</strong> on which we can “test” how well our regression model can predict high or low effect sizes.</li>
<li>In meta-regressions, we have to deal with the potential presence of effect size heterogeneity. Imagine a case in which we have two studies with different effect sizes and non-overlapping confidence intervals. Every variable which has different values for the different studies might be a potential explanation for effect size difference we find, while it seems straightforward that <strong>most of such explanations are spurious</strong> <span class="citation" data-cites="higginsControllingRiskSpurious2004">(<a href="#ref-higginsControllingRiskSpurious2004" role="doc-biblioref">J. P. T. Higgins &amp; Thompson, 2004</a>)</span>.</li>
<li>Meta-regression as such, and multiple meta-regression in particular, make it very easy to <strong>“play around” with predictors</strong>. We can test numerous meta-regression models, include many more predictors or remove them in an attempt to explain the heterogeneity in our data. Such an approach is of course tempting, and often found in practice, because we, as meta-analysts, want to find a significant model which explains why effect sizes differ <span class="citation" data-cites="higginsStatisticalHeterogeneitySystematic2002">(<a href="#ref-higginsStatisticalHeterogeneitySystematic2002" role="doc-biblioref">J. Higgins et al., 2002</a>)</span>. However, such behavior <strong>massively increases the risk of spurious findings</strong> <span class="citation" data-cites="higginsControllingRiskSpurious2004">(<a href="#ref-higginsControllingRiskSpurious2004" role="doc-biblioref">J. P. T. Higgins &amp; Thompson, 2004</a>)</span>, because we can change parts of our model indefinitely until we find a significant model, which is then very likely to be overfitted (i.e., it mostly models statistical noise).</li>
</ol>
<p><strong>Some guidelines have been proposed to avoid an excessive false positive rate when building meta-regression models:</strong></p>
<ul>
<li>Minimize the number of investigated predictors a priori. Predictor selection should be based on <strong>predefined scientific or theoretical questions</strong> we want to answer in our meta-regression.</li>
<li>When evaluating the fit of a meta-regression model, we prefer models which achieve a good fit with less predictors. Use fit indices that balance fit and parsimony, such as the <em>Akaike</em> and <em>Bayesian information criterion</em>, to determine which model to retain if you compare several models.</li>
<li>When the number of studies is low (which is very likely to be the case), and we want to compute the significance of a predictor, you can use the Knapp-Hartung adjustment to obtain more reliable estimates <span class="citation" data-cites="higginsStatisticalHeterogeneitySystematic2002">(<a href="#ref-higginsStatisticalHeterogeneitySystematic2002" role="doc-biblioref">J. Higgins et al., 2002</a>)</span>, by specifying <code>test = "knha</code> when calling <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma()</a></code>.</li>
</ul></section></section></section><section id="penalized-meta-regression" class="level1"><h1>Penalized Meta-Regression</h1>
<p>Meta-regression can be used to account for potentially relevant between-studies differences. However, we previously saw that the number of candidate moderators is often high relative to the number of studies. This introduces risks of overfitting, spurious results, and model non-convergence. Bayesian Regularized Meta-Analysis (BRMA) overcomes these challenges, selecting relevant moderators by shrinking small regression coefficients towards zero with regularizing (LASSO or horseshoe) priors <span class="citation" data-cites="vanlissaSelectingRelevantModerators2023a">(<a href="#ref-vanlissaSelectingRelevantModerators2023a" role="doc-biblioref">Van Lissa, van Erp, et al., 2023</a>)</span>. This method is suitable when there are many potential moderators, but it is not known beforehand which of them are relevant.</p>
<p>Let’s use Bayesian regularized meta-regression (BRMA) to select relevant moderators!</p>
<p>First, load in the necessary packages. If you are running the model locally on a multi-core machine, you can set <code>options(mc.cores = 4)</code>. This runs 4 MCMC chains in parallel, giving you multiple independent sampling chains while keeping estimation time relatively short.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/cjvanlissa/pema">pema</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://cjvanlissa.github.io/tidySEM/">tidySEM</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>mc.cores <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="two-level-model" class="level2"><h2 class="anchored" data-anchor-id="two-level-model">Two-level model</h2>
<p>First, for simplicity, we run a two-level BRMA model, ignoring the fact that certain effect sizes come from the same study.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df_brma</span> <span class="op">&lt;-</span> <span class="va">df</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"yi"</span>, <span class="st">"vi"</span>, <span class="va">mods</span><span class="op">)</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="two-level-model-with-the-lasso-prior" class="level3"><h3 class="anchored" data-anchor-id="two-level-model-with-the-lasso-prior">Two-level model with the lasso prior</h3>
<p>We start with running a penalized meta-analysis using the lasso prior. Compared to the horseshoe prior, the lasso is easier to use because it has only two hyperparameters to set. However, the lighter tails of the lasso can result in large coefficients being shrunken too much towards zero thereby leading to potentially more bias compared to the regularized horseshoe prior.</p>
<p>For the lasso prior, we need to specify the degrees of freedom <code>df</code> and the <code>scale</code>. Both default to 1. The degrees of freedom determines the chi-square prior that is specified for the inverse-tuning parameter. Increasing the degrees of freedom will allow larger values for the inverse-tuning parameter, leading to less shrinkage. Increasing the scale parameter will also result in less shrinkage. The influence of these hyperparameters can be visualized through the implemented shiny app, which can be called via <code><a href="https://rdrr.io/pkg/pema/man/shiny_prior.html">shiny_prior()</a></code>, and by calling <code>plot(sample_prior())</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">fit_lasso</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/pema/man/brma.html">brma</a></span><span class="op">(</span><span class="va">yi</span> <span class="op">~</span> <span class="va">.</span>,</span>
<span>                  data <span class="op">=</span> <span class="va">df_brma</span>,</span>
<span>                  vi <span class="op">=</span> <span class="st">"vi"</span>,</span>
<span>                  method <span class="op">=</span> <span class="st">"lasso"</span>,</span>
<span>                  prior <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>df <span class="op">=</span> <span class="fl">1</span>, scale <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                  mute_stan <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="assessing-convergence-and-interpreting-the-results" class="level4"><h4 class="anchored" data-anchor-id="assessing-convergence-and-interpreting-the-results">Assessing convergence and interpreting the results</h4>
<p>We can request the results using the <code>summary</code> function. Before we interpret the results, we need to ensure that the MCMC chains have converged to the posterior distribution. Two helpful diagnostics provided in the summary are the number of effective posterior samples <code>n_eff</code> and the potential scale reduction factor <code>Rhat</code>. <code>n_eff</code> is an estimate of the number of independent samples from the posterior. Ideally, the ratio <code>n_eff</code> to total samples is as close to 1 as possible. <code>Rhat</code> compares the between- and within-chain estimates and is ideally close to 1 (indicating the chains have mixed well). Should any values for <code>n_eff</code> or <code>Rhat</code> be far from these ideal values, you can try increasing the number of iterations through the <code>iter</code> argument. By default, the <code>brma</code> function runs four MCMC chains with 2000 iterations each, half of which is discarded as burn-in. As a result, a total of 4000 iterations is available on which posterior summaries are based. If this does not help, non-convergence might indicate a problem with the model specification.</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sum</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_lasso</span><span class="op">)</span></span>
<span><span class="va">sum</span><span class="op">$</span><span class="va">coefficients</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"2.5%"</span>, <span class="st">"97.5%"</span>, <span class="st">"n_eff"</span>, <span class="st">"Rhat"</span><span class="op">)</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 46%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">2.5%</th>
<th style="text-align: right;">97.5%</th>
<th style="text-align: right;">n_eff</th>
<th style="text-align: right;">Rhat</th>
<th style="text-align: left;">Sig</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">-0.10</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">3134.39</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2758.20</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">2659.68</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">locationCanada</td>
<td style="text-align: right;">-0.08</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">2341.23</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">locationCanada / South Africa</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">-0.19</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">2605.31</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">locationGermany</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">-0.29</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">2641.99</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">locationNetherlands</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">3669.31</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">locationSpain</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">-0.35</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">2868.84</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">locationUK?</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">-0.10</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">2446.27</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">locationUSA</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">2129.08</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">locationUSA/Korea</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">-0.14</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">2527.93</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">locationVanuatu</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">-0.26</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">3299.60</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">donorcodeTypical</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">3587.01</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">interventioncodeOther</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">1869.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">interventioncodeProsocial Spending</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">2594.47</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">controlcodeNothing</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">3133.02</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">controlcodeSelf Help</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">-0.12</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">3666.23</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsAnyone</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">-0.20</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">2382.21</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsAnyone / Charity</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">-0.17</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">3262.36</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsCharity</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">-0.21</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">3360.96</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsCo-Worker</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">-0.35</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">3090.35</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsColleague</td>
<td style="text-align: right;">-0.47</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">-0.98</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">2297.52</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">*</td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsFamily / Friends</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">-0.24</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">3211.15</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsFriends</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">-0.28</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">2996.24</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsOther/One</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">3164.53</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsOther/World</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">-0.17</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">2670.66</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsPuppet</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">2784.38</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsSocial Network</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">-0.38</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">3823.09</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsSomeone</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">-0.33</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">4082.22</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">recipientsSomeone known</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">3085.94</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">recipientsUnknown lab workers</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">2524.04</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">*</td>
</tr>
<tr class="even">
<td style="text-align: left;">outcomecodeLife Satisfaction</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">-0.11</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">3661.92</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">outcomecodeOther</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">-0.09</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">3835.72</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">outcomecodePN Affect</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: right;">3233.77</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">tau2</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">889.57</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">*</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If we are satisfied with the convergence, we can continue looking at the posterior summary statistics. The <code>summary</code> function provides the posterior mean estimate for the effect of each moderator. Since Bayesian penalization does not automatically shrink estimates exactly to zero, some additional criterion is needed to determine which moderators should be selected in the model. Currently, this is done using the 95% credible intervals, with a moderator being selected if zero is excluded in this interval. In the <code>summary</code> this is denoted by an asterisk for that moderator.</p>
<p>Also note the summary statistics for <code>tau2</code>, the (unexplained) residual between-studies heterogeneity.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>How many significant moderator effects are there? <input class="webex-solveme nospaces" size="1" data-answer="[&quot;2&quot;]"></p>
<p>True or false: There is significant residual heterogeneity. <select class="webex-select"><option value="blank"></option>
<option value="answer">TRUE</option>
<option value="">FALSE</option></select></p>
<p>What can we say about the coefficients of this BRMA analysis, compared to the previous <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma()</a></code> multiple regression? <select class="webex-select"><option value="blank"></option>
<option value="">The BRMA coefficients are more variable than RMA coefficients.</option>
<option value="">It is easier for coefficients to be significant in BRMA than in RMA.</option>
<option value="answer">All absolute BRMA coefficients are smaller than RMA coefficients.</option>
<option value="">The answer depends on the specific analysis.</option></select></p>
</div>
</div>
</section></section></section><section id="optional-three-level-model-with-horseshoe-prior" class="level2"><h2 class="anchored" data-anchor-id="optional-three-level-model-with-horseshoe-prior">Optional: Three-level model with Horseshoe Prior</h2>
<p>The default prior in <code><a href="https://rdrr.io/pkg/pema/man/brma.html">brma()</a></code> is the horseshoe prior, because it performed best in simulation studies. Moreover, we can take into account the fact that some effect sizes might come from the same study by fitting a three-level model as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df_brma_threelevel</span> <span class="op">&lt;-</span> <span class="va">df</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"yi"</span>, <span class="st">"vi"</span>, <span class="st">"study_id"</span>, <span class="va">mods</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">7</span><span class="op">)</span></span>
<span><span class="va">fit_hs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/pema/man/brma.html">brma</a></span><span class="op">(</span><span class="va">yi</span> <span class="op">~</span> <span class="va">.</span>,</span>
<span>               data <span class="op">=</span> <span class="va">df_brma_threelevel</span>,</span>
<span>               vi <span class="op">=</span> <span class="st">"vi"</span>,</span>
<span>               study <span class="op">=</span> <span class="st">"study_id"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="more-information" class="level3"><h3 class="anchored" data-anchor-id="more-information">More Information</h3>
<p><strong>Reference:</strong></p>
<p><span class="citation" data-cites="vanlissaSelectingRelevantModerators2023a">Van Lissa, van Erp, et al. (<a href="#ref-vanlissaSelectingRelevantModerators2023a" role="doc-biblioref">2023</a>)</span></p>
<p>For a more elaborate tutorial, see <a href="https://cjvanlissa.github.io/pema/articles/using-brma.html">this vignette</a>.</p>
</section></section></section><section id="random-forest-meta-regression" class="level1"><h1>Random Forest Meta-Regression</h1>
<p>BRMA is comparable to multiple meta-regression, with the main difference being that it shrinks coefficients towards zero to eliminate irrelevant moderators. An alternative machine learning-informed approach to moderator selection is to use tree-based methods. In this section, we use MetaForest - a random forest-based approach - to analyze the same data and select relevant moderators <span class="citation" data-cites="vanlissaSmallSampleMetaanalyses2020">(<a href="#ref-vanlissaSmallSampleMetaanalyses2020" role="doc-biblioref">Van Lissa, 2020</a>)</span>.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load the metaforest package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">metaforest</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="check-convergence" class="level3"><h3 class="anchored" data-anchor-id="check-convergence">Check Convergence</h3>
<p>For any random forest model, it is important to determine how many trees are needed to get stable results. Convergence is indicated by stabilization of the cumulative mean squared out-of-bag prediction error (MSEoob), as a function of the number of trees in the model. We run the analysis once with a very high number of trees, and pick a smaller number of trees, at which the model is also seen to have converged, to speed up computationally heavy steps, such as replication and model tuning. We re-examine convergence for the final model. Note that we can account for multiple effect sizes per study in <code>MetaForest</code> as well:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Run model with many trees to check convergence</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">74</span><span class="op">)</span></span>
<span><span class="va">check_conv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/metaforest/man/MetaForest.html">MetaForest</a></span><span class="op">(</span><span class="va">yi</span><span class="op">~</span><span class="va">.</span>,</span>
<span>data <span class="op">=</span> <span class="va">df_brma_threelevel</span>,</span>
<span>study <span class="op">=</span> <span class="st">"study_id"</span>,</span>
<span>whichweights <span class="op">=</span> <span class="st">"random"</span>,</span>
<span>num.trees <span class="op">=</span> <span class="fl">10000</span><span class="op">)</span></span>
<span><span class="co"># Plot convergence trajectory</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">check_conv</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="tutorial_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This model converges at around 2500 trees.</p>
</section><section id="model-tuning" class="level3"><h3 class="anchored" data-anchor-id="model-tuning">Model Tuning</h3>
<p>Machine learning models often have hyperparameters that must be tuned to get good performance for a specific learning task. We can tune the model using the R package <code>caret</code>. As tuning parameters, we consider all three types of weights (uniform, fixed-, and random-effects), the number of candidate variables at each split from 2–6, and a minimum node size from 2–6. We select the model with smallest root mean squared prediction error (RMSE) as the final model, based on 5-fold clustered cross-validation. Clustered cross-validation means that effect sizes from the same study are always included in the same fold, to account for the dependency in the data. Note that the number of folds cannot exceed the number of clusters in the data. Moreover, if the number of clusters is very small, one might have to resort to specifying the same number of folds as clusters. Model tuning is computationally intensive and might take a long time.</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Load caret</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/topepo/caret/">caret</a></span><span class="op">)</span></span>
<span><span class="co"># Set up 5-fold clustered CV</span></span>
<span><span class="va">grouped_cv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/caret/man/trainControl.html">trainControl</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"cv"</span>,</span>
<span>index <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/caret/man/createDataPartition.html">groupKFold</a></span><span class="op">(</span><span class="va">df_brma_threelevel</span><span class="op">$</span><span class="va">study_id</span>, k <span class="op">=</span> <span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Set up a tuning grid</span></span>
<span><span class="va">tuning_grid</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/expand.grid.html">expand.grid</a></span><span class="op">(</span>whichweights <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"random"</span>, <span class="st">"fixed"</span>, <span class="st">"unif"</span><span class="op">)</span>,</span>
<span>mtry <span class="op">=</span> <span class="fl">2</span><span class="op">:</span><span class="fl">6</span>,</span>
<span>min.node.size <span class="op">=</span> <span class="fl">2</span><span class="op">:</span><span class="fl">6</span><span class="op">)</span></span>
<span><span class="co"># X should contain only retained moderators, clustering variable, and vi</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="va">df_brma_threelevel</span><span class="op">[</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"study_id"</span>, <span class="st">"vi"</span>, <span class="va">mods</span><span class="op">)</span><span class="op">]</span></span>
<span><span class="co"># Train the model</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span>
<span><span class="va">mf_cv</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/caret/man/train.html">train</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">df_brma_threelevel</span><span class="op">$</span><span class="va">yi</span>,</span>
<span>x <span class="op">=</span> <span class="va">X</span>,</span>
<span>study <span class="op">=</span> <span class="st">"study_id"</span>, <span class="co"># Name of the clustering variable</span></span>
<span>method <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/metaforest/man/ModelInfo_mf.html">ModelInfo_mf</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>trControl <span class="op">=</span> <span class="va">grouped_cv</span>,</span>
<span>tuneGrid <span class="op">=</span> <span class="va">tuning_grid</span>,</span>
<span>num.trees <span class="op">=</span> <span class="fl">2500</span><span class="op">)</span></span>
<span><span class="co"># Best model tuning parameters</span></span>
<span><span class="va">mf_cv</span><span class="op">$</span><span class="va">results</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.min.html">which.min</a></span><span class="op">(</span><span class="va">mf_cv</span><span class="op">$</span><span class="va">results</span><span class="op">$</span><span class="va">RMSE</span><span class="op">)</span>, <span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 5%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 10%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">whichweights</th>
<th style="text-align: right;">mtry</th>
<th style="text-align: right;">min.node.size</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">Rsquared</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">RMSESD</th>
<th style="text-align: right;">RsquaredSD</th>
<th style="text-align: right;">MAESD</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">32</td>
<td style="text-align: left;">fixed</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.2760904</td>
<td style="text-align: right;">0.2936028</td>
<td style="text-align: right;">0.2240218</td>
<td style="text-align: right;">0.0861324</td>
<td style="text-align: right;">0.2951682</td>
<td style="text-align: right;">0.0671964</td>
</tr></tbody>
</table>
</div>
</div>
</div>
<p>Based on the root mean squared error, the best combination of tuning parameters were fixed-effect weights, with three candidate variables per split, and a minimum of three cases per terminal node.</p>
</section><section id="interpreting-the-results" class="level3"><h3 class="anchored" data-anchor-id="interpreting-the-results">Interpreting the Results</h3>
<p>The object returned by train already contains the final model, estimated with the best combination of tuning parameters.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Extract final model</span></span>
<span><span class="va">final</span> <span class="op">&lt;-</span> <span class="va">mf_cv</span><span class="op">$</span><span class="va">finalModel</span></span>
<span><span class="co"># Extract R^2_oob from the final model</span></span>
<span><span class="va">r2_oob</span> <span class="op">&lt;-</span> <span class="va">final</span><span class="op">$</span><span class="va">forest</span><span class="op">$</span><span class="va">r.squared</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This model has a positive estimate of explained variance in new data, <span class="math inline">\(R^2_{oob} = .19\)</span>.</p>
<p>Now, we proceed to interpreting the moderator effects, by examining variable importance and partial dependence plots. Variable importance is determined by randomly permuting each variable in turn (so it loses all meaningful association with the outcome), and then assessing how much the model’s predictive performance diminishes after this random permutation. For an important variable, the model performance drops after permutation. Partial dependence plots show the model’s predicted values at different levels of one variable, averaging over the values of all other variables. Thus, you can think of this as the bivariate marginal association.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Plot variable importance</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/metaforest/man/VarImpPlot.html">VarImpPlot</a></span><span class="op">(</span><span class="va">final</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Sort the variable names by importance</span></span>
<span><span class="va">ordered_vars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">final</span><span class="op">$</span><span class="va">forest</span><span class="op">$</span><span class="va">variable.importance</span><span class="op">)</span><span class="op">[</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">final</span><span class="op">$</span><span class="va">forest</span><span class="op">$</span><span class="va">variable.importance</span>, decreasing <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># Plot partial dependence</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/metaforest/man/PartialDependence.html">PartialDependence</a></span><span class="op">(</span><span class="va">final</span>, vars <span class="op">=</span> <span class="va">ordered_vars</span>,</span>
<span>rawdata <span class="op">=</span> <span class="cn">TRUE</span>, pi <span class="op">=</span> <span class="fl">.95</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial_files/figure-html/unnamed-chunk-31-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>What does the negative permutation importance for <code>donorcode</code> indicate? <select class="webex-select"><option value="blank"></option>
<option value="answer">Acts of Kindness</option>
<option value="">Prosocial Spending</option>
<option value="">Other</option></select></p>
<p>Which intervention has the lowest associated effect size? <select class="webex-select"><option value="blank"></option>
<option value="">This variable has a negative effect on the outcome (effect size)</option>
<option value="">Randomly permuting this variable diminishes model fit</option>
<option value="">This variable has a positive effect on the outcome (effect size)</option>
<option value="answer">Randomly permuting this variable improves model fit</option></select></p>
<p>Which variable has apparent outlier(s)? <select class="webex-select"><option value="blank"></option>
<option value="answer">age</option>
<option value="">donorcode</option>
<option value="">outcomecode</option></select></p>
</div>
</div>
</section><section id="more-information-1" class="level3"><h3 class="anchored" data-anchor-id="more-information-1">More Information</h3>
<p><strong>Reference:</strong></p>
<p><span class="citation" data-cites="vanlissaSmallSampleMetaanalyses2020">Van Lissa (<a href="#ref-vanlissaSmallSampleMetaanalyses2020" role="doc-biblioref">2020</a>)</span></p>
<p>For a more elaborate tutorial, see <a href="https://www.taylorfrancis.com/chapters/oa-edit/10.4324/9780429273872-16/small-sample-meta-analyses-caspar-van-lissa">this open access book chapter on MetaForest</a>.</p>
</section></section><section id="bayesian-evidence-synthesis" class="level1"><h1>Bayesian Evidence Synthesis</h1>
<p>Heterogeneity presents a fundamental challenge to research synthesis methods <span class="citation" data-cites="higginsReevaluationRandomeffectsMetaanalysis2009">(<a href="#ref-higginsReevaluationRandomeffectsMetaanalysis2009" role="doc-biblioref">J. P. T. Higgins et al., 2009</a>)</span>. When studies all assess the same informative hypothesis, but differ in fundamental ways that preclude aggregation through conventional meta-analysis methods, Bayesian Evidence Synthesis (BES) can be used. Consider, for example, the situation that arises when the number of moderators is very large relative to the number of studies, or when moderators are redundant (see Meta-Regression chapter above).</p>
<p>The PBF <span class="citation" data-cites="vanlissaAggregatingEvidenceConceptual2023">(<a href="#ref-vanlissaAggregatingEvidenceConceptual2023" role="doc-biblioref">Van Lissa, Kuiper, et al., 2023</a>)</span> can be used instead of random-effects meta-analysis when its assumptions were likely to be violated. This Tutorial illustrates the use of the PBF in such cases.</p>
<p>At the start of the day, we conducted random- and fixed effects meta-analyses using the function <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma()</a></code> from the <code>metafor</code> package. This required the <code>yi</code> and <code>vi</code> columns. Now, we will perform a PBF analysis using the <code><a href="https://rdrr.io/pkg/bain/man/pbf.html">pbf()</a></code> function in the <code>bain</code> package, which accepts the same arguments.</p>
<p>First, we will load the required packages.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://informative-hypotheses.sites.uu.nl/software/bain/">bain</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'bain' was built under R version 4.4.1</code></pre>
</div>
</div>
<section id="repeating-the-rma" class="level3"><h3 class="anchored" data-anchor-id="repeating-the-rma">Repeating the RMA</h3>
<p>Let’s repeat our previous random effects meta-analysis, and examing a funnel plot of the distribution of effect sizes:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">res_rma</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">yi</span>, vi <span class="op">=</span> <span class="va">vi</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="fu">metafor</span><span class="fu">::</span><span class="fu"><a href="https://wviechtb.github.io/metafor/reference/funnel.html">funnel</a></span><span class="op">(</span><span class="va">res_rma</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="tutorial_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>An effect size over 0 means that helping others increased happiness, even a little bit.</p>
<p>With a Bayes Factor, we could test the informative hypothesis (just a directional null hypothesis) that helping increases happiness in one particular study, for example the first row of the dataset:</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/bain/man/bain.html">bain</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"yi"</span> <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">yi</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span>, <span class="co"># Select the first effect size</span></span>
<span>     Sigma <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/matrix.html">matrix</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">vi</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span>, <span class="co"># Make covariance matrix</span></span>
<span>     hypothesis <span class="op">=</span> <span class="st">"yi &gt; 0"</span>, <span class="co"># Define informative hypothesis</span></span>
<span>     n <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">n1i</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">+</span><span class="va">df</span><span class="op">$</span><span class="va">n2c</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span> <span class="co"># Calculate total sample size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayesian informative hypothesis testing for an object of class numeric:

   Fit   Com   BF.u  BF.c     PMPa  PMPb  PMPc 
H1 0.999 0.500 1.999 1508.434 1.000 0.667 0.999
Hu                                  0.333      
Hc 0.001 0.500 0.001                      0.001

Hypotheses:
  H1: yi&gt;0

Note: BF.u denotes the Bayes factor of the hypothesis at hand versus the unconstrained hypothesis Hu. BF.c denotes the Bayes factor of the hypothesis at hand versus its complement. PMPa contains the posterior model probabilities of the hypotheses specified. PMPb adds Hu, the unconstrained hypothesis. PMPc adds Hc, the complement of the union of the hypotheses specified.</code></pre>
</div>
</div>
<p>The results indicate that the first study provides 1508 times more evidence <em>in favor</em> of our informative hypothesis (helping increases happiness) than against it, <span class="math inline">\(BF = 1508.434\)</span>.</p>
</section><section id="product-bayes-factor" class="level3"><h3 class="anchored" data-anchor-id="product-bayes-factor">Product Bayes Factor</h3>
<p>We now perform the PBF analysis, using the <code><a href="https://rdrr.io/pkg/bain/man/pbf.html">pbf()</a></code> method for numeric input (see <code><a href="https://rdrr.io/pkg/bain/man/pbf.html">?pbf</a></code>). This interface is very similar to <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma()</a></code>, and is specifically designed for applications where PBF is applied to meta-analytic datasets. The <code>yi</code> and <code>vi</code> arguments are the same as those of <code><a href="https://wviechtb.github.io/metafor/reference/rma.uni.html">rma()</a></code>. Additional argument <code>ni</code> is used to construct the prior for the approximate Bayes factors <span class="citation" data-cites="hoijtinkTutorialTestingHypotheses2019">(<a href="#ref-hoijtinkTutorialTestingHypotheses2019" role="doc-biblioref">Hoijtink et al., 2019</a>)</span>. Importantly, the <code>hypothesis</code> argument determines which informative hypotheses are tested.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">res_pbf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/bain/man/pbf.html">pbf</a></span><span class="op">(</span>yi <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">yi</span>,</span>
<span>               vi <span class="op">=</span> <span class="va">df</span><span class="op">$</span><span class="va">vi</span>,</span>
<span>               ni <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">df</span><span class="op">$</span><span class="va">n1i</span><span class="op">+</span><span class="va">df</span><span class="op">$</span><span class="va">n2c</span><span class="op">)</span>,</span>
<span>               hypothesis <span class="op">=</span> <span class="st">"y &gt; 0"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">PBF</th>
<th style="text-align: right;">Sample.1</th>
<th style="text-align: right;">Sample.2</th>
<th style="text-align: right;">Sample.3</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">H1: y&gt;0</td>
<td style="text-align: right;">7.449242e+69</td>
<td style="text-align: right;">1508.434</td>
<td style="text-align: right;">4.579145</td>
<td style="text-align: right;">81.31709</td>
</tr></tbody>
</table>
</div>
</div>
<p>The resulting output shows the product Bayes factors for our informative hypothesis (PBF column), as well as study-specific Bayes factors (remaining columns, trimmed here to keep the document tidy). The PBF in favor of our hypothesis is very high (a 7.45 with 69 zeroes), so the body of evidence provides consistent support for the notion that helping increases happiness.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Formative Assessment
</div>
</div>
<div class="callout-body-container callout-body">
<p>What does a negative Bayes factor indicate, for a Bayes factor comparing an informative hypothesis Hi against its complement Hc? <select class="webex-select"><option value="blank"></option>
<option value="answer">Negative Bayes factors don’t exist</option>
<option value="">The evidence for Hc outweighs the evidence for Hi</option>
<option value="">The evidence for Hi outweighs the evidence for Hc</option>
<option value="">The evidence for Hi outweighs the evidence for Hc, but the effect is negative</option></select></p>
<p>True or false: All Bayes factors must exceed one (BF &gt; 1) to obtain a PBF that also exceeds one (PBF &gt; 1) <select class="webex-select"><option value="blank"></option>
<option value="">TRUE</option>
<option value="answer">FALSE</option></select></p>
<p>True or false: A large Bayes factor means that the hypothesized effect likely exists in the population <select class="webex-select"><option value="blank"></option>
<option value="">TRUE</option>
<option value="answer">FALSE</option></select></p>
<div class="webex-solution">
<button>
Explanation
</button>
<p>This question relates to generalizability. When we perform a normal fixed- or random-effects meta-analysis, we rely on sampling theory and assume that each effect size represents a random sample from the population of possible effect sizes.</p>
<p>If this assumption is justified, then we can claim that the pooled effect size generalized to the population those effect sizes were randomly sampled from. Thus, our pooled effect size tells us something about future studies.</p>
<p>Of course, this assumption is very questionable, due to publication bias, and the fact that researchers build upon previous work! So in practice, meta-analysis might not be as generalizable as we’d like.</p>
<p>The PBF does not rely on sampling theory and does not make such assumptions about random sampling from the population. As a result, it can only be interpreted as a quantitative summary of the evidence <em>within the present sample of studies</em>.</p>
<p>It would be incorrect to interpret the PBF as saying anything about the population; we should interpret it as a summary statistic of the studies at hand. Of course, the same could be said about conventional meta-analysis, if the assumption of random sampling is violated.</p>
</div>
</div>
</div>
</section><section id="more-information-2" class="level3"><h3 class="anchored" data-anchor-id="more-information-2">More Information</h3>
<p><strong>References:</strong></p>
<p><span class="citation" data-cites="vanlissaAggregatingEvidenceConceptual2023">Van Lissa, Kuiper, et al. (<a href="#ref-vanlissaAggregatingEvidenceConceptual2023" role="doc-biblioref">2023</a>)</span></p>
<p><span class="citation" data-cites="vanlissaTeacherCornerEvaluating2020">Van Lissa et al. (<a href="#ref-vanlissaTeacherCornerEvaluating2020" role="doc-biblioref">2020</a>)</span></p>
<p>For a more elaborate tutorial on the Product Bayes Factor, see <a href="https://osf.io/preprints/psyarxiv/nvqpw">this paper, in press at Research Synthesis Methods</a>.</p>
</section><section id="credit" class="level2"><h2 class="anchored" data-anchor-id="credit">Credit</h2>
<p>This tutorial is partly based on the book <em>Doing Meta-Analysis with R: A Hands-On Guide</em>, which is also recommended as further reading:</p>
<blockquote class="blockquote">
<p>Harrer, M., Cuijpers, P., Furukawa, T.A., &amp; Ebert, D.D. (2021). <em>Doing Meta-Analysis with R: A Hands-On Guide</em>. Boca Raton, FL and London: Chapmann &amp; Hall/CRC Press. ISBN 978-0-367-61007-4.</p>
</blockquote>

</section></section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list">
<div id="ref-borensteinIntroductionMetaAnalysis2009" class="csl-entry" role="listitem">
Borenstein, M., Hedges, L. V., Higgins, J. P. T., &amp; Rothstein, H. R. (2009). <em>Introduction to <span>Meta-Analysis</span></em>. John Wiley &amp; Sons, Ltd. <a href="https://doi.org/10.1002/9780470743386">https://doi.org/10.1002/9780470743386</a>
</div>
<div id="ref-hastieElementsStatisticalLearning2009" class="csl-entry" role="listitem">
Hastie, T., Tibshirani, R., &amp; Friedman, J. (2009). <em>The elements of statistical learning: <span>Data</span> mining, inference, and prediction</em> (Second). Springer.
</div>
<div id="ref-higginsControllingRiskSpurious2004" class="csl-entry" role="listitem">
Higgins, J. P. T., &amp; Thompson, S. G. (2004). Controlling the risk of spurious findings from meta-regression. <em>Statistics in Medicine</em>, <em>23</em>(11), 1663–1682. <a href="https://doi.org/10.1002/sim.1752">https://doi.org/10.1002/sim.1752</a>
</div>
<div id="ref-higginsReevaluationRandomeffectsMetaanalysis2009" class="csl-entry" role="listitem">
Higgins, J. P. T., Thompson, S. G., &amp; Spiegelhalter, D. J. (2009). A re-evaluation of random-effects meta-analysis. <em>Journal of the Royal Statistical Society. Series A, (Statistics in Society)</em>, <em>172</em>(1), 137–159. <a href="https://doi.org/10.1111/j.1467-985X.2008.00552.x">https://doi.org/10.1111/j.1467-985X.2008.00552.x</a>
</div>
<div id="ref-higginsStatisticalHeterogeneitySystematic2002" class="csl-entry" role="listitem">
Higgins, J., Thompson, S., Deeks, J., &amp; Altman, D. (2002). Statistical heterogeneity in systematic reviews of clinical trials: A critical appraisal of guidelines and practice. <em>Journal of Health Services Research &amp; Policy</em>, <em>7</em>(1), 51–61. <a href="https://doi.org/10.1258/1355819021927674">https://doi.org/10.1258/1355819021927674</a>
</div>
<div id="ref-hoijtinkTutorialTestingHypotheses2019" class="csl-entry" role="listitem">
Hoijtink, H., Mulder, J., van Lissa, C., &amp; Gu, X. (2019). A tutorial on testing hypotheses using the <span>Bayes</span> factor. <em>Psychological Methods</em>, <em>24</em>(5), 539–556. <a href="https://doi.org/10.1037/met0000201">https://doi.org/10.1037/met0000201</a>
</div>
<div id="ref-schwarzerMetaAnalysis2015" class="csl-entry" role="listitem">
Schwarzer, G., Carpenter, J. R., &amp; Rücker, G. (2015). <em>Meta-<span>Analysis</span> with <span>R</span></em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-319-21416-0">https://doi.org/10.1007/978-3-319-21416-0</a>
</div>
<div id="ref-vanlissaSmallSampleMetaanalyses2020" class="csl-entry" role="listitem">
Van Lissa, C. J. (2020). Small sample meta-analyses: <span>Exploring</span> heterogeneity using <span>MetaForest</span>. In R. Van De Schoot &amp; M. Miočević (Eds.), <em>Small <span>Sample Size Solutions</span> (<span>Open Access</span>): <span>A Guide</span> for <span>Applied Researchers</span> and <span>Practitioners</span></em>. CRC Press.
</div>
<div id="ref-vanlissaTeacherCornerEvaluating2020" class="csl-entry" role="listitem">
Van Lissa, C. J., Gu, X., Mulder, J., Rosseel, Y., Zundert, C. V., &amp; Hoijtink, H. (2020). Teacher’s <span>Corner</span>: <span>Evaluating Informative Hypotheses Using</span> the <span>Bayes Factor</span> in <span>Structural Equation Models</span>. <em>Structural Equation Modeling: A Multidisciplinary Journal</em>, <em>0</em>(0), 1–10. <a href="https://doi.org/10.1080/10705511.2020.1745644">https://doi.org/10.1080/10705511.2020.1745644</a>
</div>
<div id="ref-vanlissaAggregatingEvidenceConceptual2023" class="csl-entry" role="listitem">
Van Lissa, C. J., Kuiper, R. M., &amp; Clapper, E.-B. (2023). <em>Aggregating evidence from conceptual replication studies using the product <span>Bayes</span> factor</em> [Preprint]. PsyArXiv. <a href="https://doi.org/10.31234/osf.io/nvqpw">https://doi.org/10.31234/osf.io/nvqpw</a>
</div>
<div id="ref-vanlissaSelectingRelevantModerators2023a" class="csl-entry" role="listitem">
Van Lissa, C. J., van Erp, S., &amp; Clapper, E.-B. (2023). Selecting relevant moderators with <span>Bayesian</span> regularized meta-regression. <em>Research Synthesis Methods</em>, <em>14</em>(2), 301–322. <a href="https://doi.org/10.1002/jrsm.1628">https://doi.org/10.1002/jrsm.1628</a>
</div>
<div id="ref-viechtbauerConductingMetaanalysesMetafor2010" class="csl-entry" role="listitem">
Viechtbauer, W. (2010). Conducting meta-analyses in <span>R</span> with the metafor package. <em>Journal of Statistical Software</em>, <em>36</em>(3), 1–48. <a href="http://www.jstatsoft.org/v36/i03/">http://www.jstatsoft.org/v36/i03/</a>
</div>
</div></section></div></main><!-- /main column --><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script>
// open rdrr links externally ----

var exlinks = document.querySelectorAll("a[href^='https://rdrr.io']");
var exlink_func = function(){
  window.open(this.href);
  return false;
};
for (var i = 0; i < exlinks.length; i++) {
    exlinks[i].addEventListener('click', exlink_func, false);
}

// visible second sidebar in mobile ----

function move_sidebar() {
  var toc = document.getElementById("TOC");
  var small_sidebar = document.querySelector("#quarto-sidebar .sidebar-menu-container");
  var right_sidebar = document.getElementById("quarto-margin-sidebar");

  if (window.innerWidth < 768) {
    small_sidebar.append(toc);
  } else {
    right_sidebar.append(toc);
  }
}
move_sidebar();
window.onresize = move_sidebar;
</script><script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>